# Streamlit secrets - DO NOT commit real secrets to the repository.
# Add your Gemini API key here when running locally, or set the key in
# Streamlit Cloud's Secrets (recommended) or your environment variables.
# Example (uncomment and set your key locally only for testing):
# GEMINI_API_KEY = "AIzaSyBHOTfbLkt0rQpNRJa6418S9ueuwcgAOIM"
